@echo off
echo.
echo === Contact Form Email Setup ===
echo.
echo This will create your .env.local file with email credentials.
echo.
echo You need:
echo 1. Your Gmail address
echo 2. A Gmail App Password (get it from: https://myaccount.google.com/apppasswords)
echo 3. The receiver email address
echo.
echo.

set /p EMAIL_USER="Enter your Gmail address (sender): "
set /p EMAIL_PASS="Enter your Gmail App Password (16 characters): "
set /p RECEIVER_EMAIL="Enter receiver email address [rishibose00@gmail.com]: "

if "%RECEIVER_EMAIL%"=="" set RECEIVER_EMAIL=rishibose00@gmail.com

echo.
echo Creating .env.local file...
echo.

(
echo # Email Configuration for Contact Form
echo # Auto-generated by setup-env.bat
echo.
echo EMAIL_USER=%EMAIL_USER%
echo EMAIL_PASS=%EMAIL_PASS%
echo RECEIVER_EMAIL=%RECEIVER_EMAIL%
) > .env.local

echo.
echo ✓ .env.local file created successfully!
echo.
echo Next steps:
echo 1. If your dev server is running, restart it (Ctrl+C then 'npm run dev')
echo 2. Test the contact form on your website
echo.
echo To verify the setup, run: node check-env.js
echo.
pause
